// <auto-generated />
using API_Farm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Farm.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240918131259_CreatedDataForTheAnimalTypesDatabase")]
    partial class CreatedDataForTheAnimalTypesDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_Farm.Models.AnimalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("animal_types");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Description = "vertebrado de sangre fria con escamas",
                            Name = "reptil"
                        },
                        new
                        {
                            Id = 7,
                            Description = "animales que beben leche",
                            Name = "mamifero"
                        },
                        new
                        {
                            Id = 8,
                            Description = "animales que consumen exclusivamente carne",
                            Name = "carnivoros"
                        },
                        new
                        {
                            Id = 9,
                            Description = "animales que consumen tanto carne como plantas",
                            Name = "ominvoros"
                        },
                        new
                        {
                            Id = 10,
                            Description = "animales que consumen exclusivamente plantas",
                            Name = "herbivoros"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
